/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.prijavljivanje;

import forms.Glavna_formaa;
import forms.prijavljivanje.PretragaPrijavljivanjeForma;
import java.net.SocketException;
import kontrolor.Kontrolor;
import model.Prijavljivanje;
import model.Kurs;
import model.NastavniProgram;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Student;
import table.model.TableModelKursevi;

/**
 *
 * @author ivana
 */
public class DetaljiPrijavljivanjaForma extends javax.swing.JDialog {

    private Prijavljivanje p;
    private double ukupnaCena;
    ArrayList<NastavniProgram> programi;
    
    /**
     * Creates new form DetaljiIznajmljivanjaForm
     */
    public DetaljiPrijavljivanjaForma(javax.swing.JDialog parent, boolean modal,Prijavljivanje p) {
        super(parent, modal);
        JOptionPane.showMessageDialog(this, "Sistem je učitao prijavljivanje.");

        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Detalji prijavljivanja");
        this.p=p;
        
        popuniPrograme();
        
        popuniFormu();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxProgrami = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBrojESPB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCenaESPB = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKursevi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUkupnaCena = new javax.swing.JTextField();
        jButtonZatvori = new javax.swing.JButton();
        jButtonOtkaziPrijavljivanje = new javax.swing.JButton();
        jButtonIzmeniPrijavljivanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(190, 215, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalji prijavljivanja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Student:");

        jLabel2.setText("Datum prijavljivanja");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unesi kurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        jLabel3.setText("Nastavni program");

        jLabel4.setText("Broj ESPB");

        jTextFieldBrojESPB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBrojESPBKeyReleased(evt);
            }
        });

        jLabel5.setText("Cena ESPB");

        jButtonDodaj.setText("DODAJ KURS");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("OBRISI KURS");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jTableKursevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKursevi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxProgrami, 0, 385, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCenaESPB)
                                    .addComponent(jTextFieldBrojESPB)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxProgrami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBrojESPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCenaESPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Ukupan iznos");

        jButtonZatvori.setText("Zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        jButtonOtkaziPrijavljivanje.setText("Otkaži prijavu");
        jButtonOtkaziPrijavljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziPrijavljivanjeActionPerformed(evt);
            }
        });

        jButtonIzmeniPrijavljivanje.setText("Izmeni prijavu");
        jButtonIzmeniPrijavljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniPrijavljivanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOtkaziPrijavljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzmeniPrijavljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonOtkaziPrijavljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIzmeniPrijavljivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOtkaziPrijavljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziPrijavljivanjeActionPerformed
       
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da otkazete prijavljivanje?", "Otkazivanje", JOptionPane.YES_NO_OPTION);
        
        if(result==JOptionPane.NO_OPTION){
            return;
        }
        
        if(result==JOptionPane.YES_OPTION){
        
            try {
                Kontrolor.getInstance().deletePrijavljivanje(p);
                PretragaPrijavljivanjeForma forma= (PretragaPrijavljivanjeForma) getParent();
                forma.refreshTable();
                JOptionPane.showMessageDialog(this, "Sistem je obrisao prijavljivanje.");
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da obriše prijavljivanje.");

                Logger.getLogger(DetaljiPrijavljivanjaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonOtkaziPrijavljivanjeActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        
       NastavniProgram izabraniProgram=new NastavniProgram();
        
       String nazivPrograma= (String) jComboBoxProgrami.getSelectedItem();
       for(int i=0;i<programi.size();i++){
            if(programi.get(i).getNaziv().equals(nazivPrograma)){
                
                izabraniProgram=programi.get(i);
            }
        }
       
        int brojESPB= Integer.parseInt(jTextFieldBrojESPB.getText());
        double cenaESPB= Double.parseDouble(jTextFieldCenaESPB.getText());
        
        Kurs k= new Kurs(-1, brojESPB, cenaESPB, izabraniProgram, p);
        TableModelKursevi tm = (TableModelKursevi) jTableKursevi.getModel();
        tm.dodajKurs(k);
        
        ukupnaCena= tm.vratiUkupnuCenu();
        jTextFieldUkupnaCena.setText(String.valueOf(ukupnaCena));
        
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jTextFieldBrojESPBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBrojESPBKeyReleased
        
//        
//        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
//        
//        NastavniProgram program = (NastavniProgram) jComboBoxProgrami.getSelectedItem();
//        int brojESPB= Integer.parseInt(jTextFieldBrojESPB.getText());
        
       // double cenaESPB = brojESPB* program.getCenaESPB(); //?????
       // jTextFieldCenaESPB.setText(String.valueOf(cena));
        
//        }
        
//        else {
//            
//            jTextFieldBrojESPB.setText("");
//            jTextFieldCenaESPB.setText("");
//            
//        }
    }//GEN-LAST:event_jTextFieldBrojESPBKeyReleased

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        
        int red= jTableKursevi.getSelectedRow();
        
        if(red>=0){
            
        TableModelKursevi tm=  (TableModelKursevi) jTableKursevi.getModel();
        
        tm.obrisiKurs(red);
        ukupnaCena=tm.vratiUkupnuCenu();
        jTextFieldUkupnaCena.setText(String.valueOf(ukupnaCena));
            
        }
                
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonIzmeniPrijavljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniPrijavljivanjeActionPerformed
              Student izabraniStudent=new Student();  
        try {
           
            SimpleDateFormat sdf= new SimpleDateFormat("dd.MM.yyyy");
            Date datum =sdf.parse(jTextFieldDatum.getText());
            TableModelKursevi tm= (TableModelKursevi) jTableKursevi.getModel();
            p.setStudent(izabraniStudent);
            p.setDatumPrijavljivanja(datum); 
            p.setKurs(tm.getLista());
            p.setUkupnaCena(ukupnaCena);
            
            Kontrolor.getInstance().updatePrijavljivanje(p);
            PretragaPrijavljivanjeForma forma= (PretragaPrijavljivanjeForma) getParent();
            forma.refreshTable();
            
            JOptionPane.showMessageDialog(this, "Sistem je izmenio prijavljivanje.");
            this.dispose();
            
        } catch (SocketException ex) {
        JOptionPane.showMessageDialog(this, "Veza sa serverom je prekinuta. Pokušajte ponovo kasnije.", "Greška", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        Logger.getLogger(DetaljiPrijavljivanjaForma.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni prijavljivanje.");
    }
        
        
    }//GEN-LAST:event_jButtonIzmeniPrijavljivanjeActionPerformed

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeniPrijavljivanje;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOtkaziPrijavljivanje;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JComboBox<String> jComboBoxProgrami;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKursevi;
    private javax.swing.JTextField jTextFieldBrojESPB;
    private javax.swing.JTextField jTextFieldCenaESPB;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldUkupnaCena;
    // End of variables declaration//GEN-END:variables

    

    private void popuniPrograme() {
        try {
            jComboBoxProgrami.removeAllItems();
            
            programi=Kontrolor.getInstance().getAllNastavniPrograms();
            
            for(NastavniProgram np:programi){
                jComboBoxProgrami.addItem(np.toString());
            }
        } catch (Exception ex) {
            Logger.getLogger(Glavna_formaa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    private void popuniFormu() {
        
        jLabel1.setText("Student: " + p.getStudent().getIme()+ " " + p.getStudent().getPrezime());
        SimpleDateFormat sdf= new SimpleDateFormat("dd.MM.yyyy");
        jTextFieldDatum.setText(sdf.format(p.getDatumPrijavljivanja()));
        ukupnaCena= p.getUkupnaCena();
        jTextFieldUkupnaCena.setText(String.valueOf(ukupnaCena));
//        jTextFieldBrojESPB.setText();
//        jTextFieldCenaESPB.setEditable(true);
        jTextFieldUkupnaCena.setEditable(false);
       
        
        jTableKursevi.setModel(new TableModelKursevi(p));
    }
}
