/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.student;

import kontrolor.Kontrolor;
import model.Student;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ivana
 */
public class DetaljiStudentaForma extends javax.swing.JDialog {

    private Student s;

    /**
     * Creates new form DetaljiKorisnikaForm
     */
    public DetaljiStudentaForma(javax.swing.JDialog parent, boolean modal, Student s) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Detalji o studentu");
        JOptionPane.showMessageDialog(this,"Sistem je učitao studenta.");
        this.s = s;
        jTextField1.setText(s.getIme());
        jTextField2.setText(s.getPrezime());
        jTextField3.setText(s.getEmail());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButtonOTKAZI = new javax.swing.JButton();
        jButtonOBRISI = new javax.swing.JButton();
        jButtonIZMENI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(190, 215, 220));

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Email");

        jButtonOTKAZI.setText("Otkazi");
        jButtonOTKAZI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOTKAZIActionPerformed(evt);
            }
        });

        jButtonOBRISI.setText("Obriši studenta");
        jButtonOBRISI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOBRISIActionPerformed(evt);
            }
        });

        jButtonIZMENI.setText("Izmeni studenta");
        jButtonIZMENI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIZMENIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonOTKAZI, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonOBRISI, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIZMENI, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOTKAZI)
                    .addComponent(jButtonOBRISI)
                    .addComponent(jButtonIZMENI))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOBRISIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOBRISIActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete korisnika?", "Brisanje korisnika", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }
        if (result == JOptionPane.YES_OPTION) {

            try {
                Kontrolor.getInstance().deleteStudent(s);
                PretragaStudentaForma formar = (PretragaStudentaForma) getParent();
                formar.osveziTabelu();
                formar.popuniStudente();
                JOptionPane.showMessageDialog(this, "Sistem je obrisao studenta!");
                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da obriše studenta.");
                Logger.getLogger(DetaljiStudentaForma.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButtonOBRISIActionPerformed

    private void jButtonOTKAZIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOTKAZIActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOTKAZIActionPerformed

    private void jButtonIZMENIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIZMENIActionPerformed

        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni studenta.");
            return;
        }

        String ime = jTextField1.getText();
        String prezime = jTextField2.getText();
        String email = jTextField3.getText();

        
        s.setIme(ime);
        s.setPrezime(prezime);
        s.setEmail(email);

        try {
            Kontrolor.getInstance().updateStudent(s);
            PretragaStudentaForma form = (PretragaStudentaForma) getParent();
            form.osveziTabelu();
            form.popuniStudente();
            JOptionPane.showMessageDialog(this, "Sistem je izmenio podatke studenta.");
            this.dispose();

        } catch (Exception ex) {
            Logger.getLogger(DetaljiStudentaForma.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonIZMENIActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIZMENI;
    private javax.swing.JButton jButtonOBRISI;
    private javax.swing.JButton jButtonOTKAZI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
