/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import kontrolor.Kontrolor;
import model.Predavac;
import session.Session;

/**
 *
 * @author ivana
 */
public class LOGIN_form extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_form
     */
    public LOGIN_form() {
        
        initComponents();
        setLocationRelativeTo(null); //pozicionira login formu na centar ekrana, kada prosledimo null znaci relative to nothing
        setTitle("Prijava na sistem");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsername1 = new javax.swing.JTextField();
        jButtonPrijaviSe = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelSLIKA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(601, 330));
        setPreferredSize(new java.awt.Dimension(610, 310));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsername1.setText("ivana123");
        jTextFieldUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsername1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 189, 30));

        jButtonPrijaviSe.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButtonPrijaviSe.setText("PRIJAVI SE");
        jButtonPrijaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrijaviSeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrijaviSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 108, 31));

        jButtonOtkazi.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jButtonOtkazi.setText("OTKAŽI");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOtkazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 98, 31));

        jPasswordField1.setText("ivana123");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(64, 26));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 190, 30));

        jLabelSLIKA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/LOGINform.png"))); // NOI18N
        getContentPane().add(jLabelSLIKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrijaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrijaviSeActionPerformed
        // TODO add your handling code here:
        try{
            
        String username=jTextFieldUsername1.getText();
        String password=String.valueOf(jPasswordField1.getPassword());
        
        Predavac p=new Predavac();
        p.setUsername(username);
        p.setPassword(password);
        
        Predavac predavac=Kontrolor.getInstance().login(p);
        Session.getInstance().setUlogovani(predavac);
        
        new Glavna_formaa().setVisible(true);
        this.dispose();
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Neuspešna registracija, molimo Vas pokušajte ponovo!", "LOGIN", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPrijaviSeActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jTextFieldUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsername1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LOGIN_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonPrijaviSe;
    private javax.swing.JLabel jLabelSLIKA;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUsername1;
    // End of variables declaration//GEN-END:variables
}
